### ISSUE TITLE
App doesn't load properly on 10.10

### ISSUE THREAD

**Issue by justvanrossum** [ronaldoussoren/py2app#281] opened 2020-02-14 12:05 UTC
Warnings issued:

```
Failed to connect (colorGridView) outlet from (NSApplication) to (NSColorPickerGridView): missing setter or instance variable
Failed to connect (view) outlet from (NSApplication) to (NSColorPickerGridView): missing setter or instance variable
```

The app doesn't crash or exit, but the menus aren't loaded.

The same app runs fine on 10.15. This is a regression from py2app 0.19 and appeared in 0.20 and still exists in 0.21.

I'll try to make a minimal app to reproduce.

**Comment by justvanrossum** [comment] 2020-02-14 12:20
Here's a minimal project that demonstrates the issue:

[py2app_issue281.zip](https://github.com/ronaldoussoren/py2app/files/4204400/py2app_issue281.zip)

**Comment by ronaldoussoren** [comment] 2020-02-16 11:47
This is probably related to #269 and #276: I changed the stub executable used in app bundles to fix an incompatibility with Python 3.8 (#269), and later rebuild the exectutables on an older version of macOS to fix a problem with Tkinter (#276). 

I guess it is time to launch an even older VM to rebuild the stub executable there as a quick fix (postponing researching how I can build executables on a recent macOS version without introducing problems until later).

**Comment by justvanrossum** [comment] 2020-03-03 15:33
I have a machine running 10.10 handy, let me know if I can do anything.

**Comment by justvanrossum** [comment] 2020-09-07 18:27
Ping! Can I help with this issue in one way or another? This issue blocks my project from upgrading to Python 3.8, unless I am willing to drop support for macOS 10.10. Does py2app still intend to support 10.10?

**Comment by ronaldoussoren** [comment] 2020-09-11 09:32
I've been busy with other projects.  Looks like the easy workaround is to rebuild the stub executables on a 10.9 system, I'm doing that today.

I still intent to support macOS 10.9 or later.

**Comment by ronaldoussoren** [comment] 2020-09-14 09:24
Could you test if the version in the repository fixes the issue for you? 

I've rebuild the stub executables on macOS 10.9 in changeset 8ca33e3cdc7ec9e2219ee14ef3ba3740d9399c97

Next up: investigate why my 10.10 VM doesn't work anymore...

**Comment by justvanrossum** [comment] 2020-09-14 10:05
Unfortunately not: I still get the same warnings and behavior (the app starts, but apart from the Apple menu and the app menu (which is empty) no menus appear).

**Comment by ronaldoussoren** [comment] 2020-09-14 10:29
I'll actually have to debug the issue then. The good news is that I have found an older copy of my 10.10 VM that works properly, which means I can debug this myself.

**Comment by ronaldoussoren** [comment] 2020-09-15 08:41
I can reproduce the issue on my 10.9 test VM, both with PyObjC installed from wheels and PyObjC installed from source.

The issue is also reproducible using the "TinyTinyEdit" example in the py2app repo, which is old and used to work without problems.

This makes it highly likely that the issue is in the py2app stub executable.

**Comment by ronaldoussoren** [comment] 2020-09-15 09:03
- Issue is not fixed by using stub executable from py2app 0.19 (using Python 3.7)
- Issue is fixed by using all of py2app 0.19 (using Python 3.7)
- Issue is not fixed by using py2app 0.20 (using Python 3.7)

=> One of the changes between 0.19 and 0.20 causes the problem, but likely not the change to the stub executable.

**Comment by ronaldoussoren** [comment] 2020-09-15 09:19
I've reverted the plist template to the one in py2app 0.19  and that seems to fix the issue.

@justvanrossum : Could you test if it also fixes the issue for you?

**Comment by justvanrossum** [comment] 2020-09-15 09:28
Yes it does, hallelujah! Thank you so much!

**Comment by ronaldoussoren** [comment] 2020-09-15 09:48
Sigh... That file should have no changes other than code style.  I clearly did more than that :-(.

My current plan is to push out a new release tonight.

**Comment by ronaldoussoren** [comment] 2020-09-16 09:18
py2app 0.22 is now on PyPI

**Closed by ronaldoussoren** 2020-09-16 09:18 UTC
