### ISSUE TITLE
Sharing not easily possible

### ISSUE THREAD

**Issue by StefanJordan** [ronaldoussoren/py2app#493] opened 2023-06-13 09:14 UTC
I agree with https://github.com/ronaldoussoren/py2app/issues/492

Any zipping destroys the app completely.

Instead of converting the app to a zip file, I tried converting it to a dmg file, which prevented the app from being destroyed. However, when attempting to open the app after conversion, a "App is damaged and can't be opened. You should move it to the Trash" error occurs on Mac.

To address this issue, I discovered that executing the command "sudo xattr -cr /path_to_App/App.app" allows the app to be opened successfully. Nevertheless, I believe this is not an optimal solution. 

I'm working with Ventura 13.4. If anyone has a better solution to this problem, I would appreciate your input.

**Comment by ronaldoussoren** [comment] 2023-06-13 09:31
I'm closing this issue as a duplicate of #492. 

As mentioned in that issue: this appears to be the quarantine system on macOS interfering. That subsystem has annoyingly vague error messages when it disapproves of an application bundle. 

Removing extended attributes ensures that the quarantine system isn't triggered, but that's just a workaround for the problem and not a fix.

**Closed** 2023-06-13 09:31 UTC
