### ISSUE TITLE
Macbook M1: Big Sur: Alias mode OK but redistributable crashes.

### ISSUE THREAD

**Issue by dansamber** [ronaldoussoren/py2app#345] opened 2021-04-06 18:33 UTC
Am trying py2app for the first time and although running in "alias mode" works fine, the fully compiled version intended for distribution crashes immediately. Could it have something to do with the ARM processor? I tried running with Rosetta but that didn't seem to make a difference. 

I'm running Mac OS 11.2.3 (Big Sur) with Python 3.8.8 and Pyqt5

Thanks!

Dan

**Comment by MCMi460** [comment] 2021-05-13 20:39
I have this error as well. The redistributable is perfectly fine without PyQt5, however it returns a non-zero exit status with this error code when I add PyQt5:
`bundle format unrecognized, invalid, or unsuitable`
The alias mode works well, but I am hoping to package it for other users to use in the future.
I am also on Apple Silicon.

**Comment by fishbacp** [comment] 2021-06-15 18:37
Similar problem here using Big Sur (Macbook Pro), Python 3.9, and py2app .24. I'm not using PyQt in my script but tkinter. No problem developing and running in alias mode, but redistributable crashes with error code:

 ```
 File "pandas/_libs/testing.pyx", line 1, in init pandas._libs.testing
ValueError: source code string cannot contain null bytes
```

My Pandas is up-to-date.

**Comment by ronaldoussoren** [comment] 2021-09-15 08:48
I don't know what's going on here, and I need more information to try to reproduce.

- What version of Python do you use?  
- How was Python installed (python.org installer, homebrew, ...)?
- What's the result of ``sysconfig.get_platform()``
- How did you install PyQt5
- Do you have a sample project that reproduces the problem (and that you can share)?

The pandas issue is likely fixed in the upcoming 0.26 release (can be tested by installing from this repo).

**Comment by MCMi460** [comment] 2021-09-15 23:46
It's been awhile, so for whatever reason the error has changed. Likely due to something updating. This time, I don't actually get an error message from py2app or Python. Instead, it compiles fine, but when running it, MacOS returns an error. To be clear, it is the `.app` in `./dist` I am running.
`sysconfig.get_platform()` returns `macosx-11-arm64`.
Here's my `setup.py`:
```py
from setuptools import setup

APP = ['pyqt.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'CFBundleName': 'PyQt Test',
        'CFBundleShortVersionString': '1.0.0',
        'LSUIElement': False,
    },
    'packages': ['PyQt5'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
```
Here's the sample code I've been using:
```py
import sys
from time import sleep

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (
    QApplication,
    QLabel,
    QMainWindow,
    QPushButton,
    QVBoxLayout,
    QWidget,
)

class Window(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.clicksCount = 0
        self.setupUi()

    def setupUi(self):
        self.setWindowTitle("Freezing GUI")
        self.resize(300, 150)
        self.centralWidget = QWidget()
        self.setCentralWidget(self.centralWidget)
        # Create and connect widgets
        self.clicksLabel = QLabel("Counting: 0 clicks", self)
        self.clicksLabel.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.stepLabel = QLabel("Long-Running Step: 0")
        self.stepLabel.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.countBtn = QPushButton("Click me!", self)
        self.countBtn.clicked.connect(self.countClicks)
        self.longRunningBtn = QPushButton("Long-Running Task!", self)
        self.longRunningBtn.clicked.connect(self.runLongTask)
        # Set the layout
        layout = QVBoxLayout()
        layout.addWidget(self.clicksLabel)
        layout.addWidget(self.countBtn)
        layout.addStretch()
        layout.addWidget(self.stepLabel)
        layout.addWidget(self.longRunningBtn)
        self.centralWidget.setLayout(layout)

    def countClicks(self):
        self.clicksCount += 1
        self.clicksLabel.setText(f"Counting: {self.clicksCount} clicks")

    def reportProgress(self, n):
        self.stepLabel.setText(f"Long-Running Step: {n}")

    def runLongTask(self):
        """Long-running task in 5 steps."""
        for i in range(5):
            sleep(1)
            self.reportProgress(i + 1)

app = QApplication(sys.argv)
win = Window()
win.show()
sys.exit(app.exec())
```

**Comment by ronaldoussoren** [comment] 2021-09-16 10:17
I haven't tried debugging this yet, but have a quick first reaction: Don't use the argv_emulation option, that's not compatible with GUI libraries. Until recently the py2app documentation suggested to use the option by default, but that advise has changed.

For Qt specifically, see: https://doc.qt.io/qtforpython-5/PySide2/QtGui/QFileOpenEvent.html, this allows your application to react to file-open events even after the application has launched.

**Comment by ronaldoussoren** [comment] 2021-09-17 09:12
I get an error as well:

$ dist/PyQt\ Test.app/Contents/MacOS/PyQt\ Test 
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

This is with python 3.9  and PyQt5 installed through homebrew. The program works fine when using the python.org installer and PyQt5 from PyPI.  This is in a x86_64 VM running Big Sur.

Next up: investigate what's going on...

**Comment by ronaldoussoren** [comment] 2021-09-18 10:16
Could you test if the version in the repository fixes the issue for you? I tweaked the PyQt5 recipe to detect that Qt itself is installed outside of the PyQt5 package (as it is with homebrew) and copy some more stuff into the app bundle in that case.

That results in a working app bundle using the reproducer you created (thanks for that btw.).

I made the same change for the PyQt6 recipe as well, but haven't tested that. That change should be obviously correct...

**Comment by MCMi460** [comment] 2021-09-18 21:18
It works great now, thank you!

**Comment by ronaldoussoren** [comment] 2021-09-19 09:44
Great. I've uploaded py2app 0.26 to PyPI and that includes this fix.

**Closed by ronaldoussoren** 2021-09-19 09:44 UTC

**Comment by vianfbrtr** [comment] 2022-02-28 10:33
sorry, but i still gettin' the same error saying "qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."

i'm installing pyqt5 using pip on venv and bundling it via py2app on the same venv. 

what should i do?

**Comment by alisrn** [comment] 2022-09-20 21:31
I have a similar problem in M1 Monterey.
App works fine with alias and also build is successful for the deployment but the app crashes immediately.

Here is my sample code.

```
import pandas as pd
from datetime import datetime, timedelta
date = '2022-09-20'
run_date = pd.to_datetime(date)
begin_date = run_date + timedelta(days=-8) 
```

Here is my setup.py
```
from setuptools import setup

APP = ['Run_Turkia_Consumption.py']
DATA_FILES = ['turkia_consumption_model.pkl']
PKGS = ['pandas', 'datetime']
OPTIONS = {
    'packages': PKGS,
    'includes': PKGS
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'pandas', 'datetime'],
)
```

Here is the error I got when I open the app from the console, `dist/myApp.app/Contents/myApp`:
```
Traceback (most recent call last):
  File "/Users/ali/Documents/ttt/app/dist/myApp.app/Contents/Resources/__boot__.py", line 147, in <module>
    _setup_ctypes()
  File "/Users/ali/Documents/ttt/app/dist/myApp.app/Contents/Resources/__boot__.py", line 140, in _setup_ctypes
    from ctypes.macholib import dyld
  File "ctypes/__init__.pyc", line 8, in <module>
ImportError: dlopen(/Users/ali/Documents/ttt/app/dist/myApp.app/Contents/Resources/lib/python3.10/lib-dynload/_ctypes.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
  Referenced from: /Users/ali/Documents/ttt/app/dist/myApp.app/Contents/Resources/lib/python3.10/lib-dynload/_ctypes.so
  Reason: tried: '/Users/ali/Documents/ttt/app/dist/myApp.app/Contents/Resources/lib/python3.10/lib-dynload/../../libffi.8.dylib' (no such file), '/Users/ali/Documents/ttt/app/dist/myApp.app/Contents/Resources/lib/python3.10/lib-dynload/../../libffi.8.dylib' (no such file), '/Users/ali/Documents/ttt/app/dist/myApp.app/Contents/Frameworks/libffi.8.dylib' (no such file), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file)
2022-09-21 00:23:31.603 myApp[95510:2545400] Launch error
2022-09-21 00:23:31.603 myApp[95510:2545400] Launch error
See the py2app website for debugging launch issues
```

**Comment by jczic** [comment] 2022-10-14 16:47
I've the same on Mac M1, but I copied "libffi.8.dylib" to the frameworks directory in the bundle and the .app works, just on my computer... And doesn't works on an another MacM1 (with Monterey).
